name: Send Email with Quote

on:
  push:
    branches:
      - main # Ganti dengan nama branch yang Anda inginkan

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Get Quote
        id: get_quote
        run: |
          response=$(curl -s -H "X-Api-Key: 3s/x4frit3GOGhj4NgYgvQ==ADMCEqbcW7LGZalp" https://api.api-ninjas.com/v1/quotes)          
          echo "Response: $response"  # Untuk debugging        
          quote=$(echo $response | jq -r '.[0].quote')  # Ambil kutipan dari elemen pertama        
          author=$(echo $response | jq -r '.[0].author')  # Ambil penulis dari elemen pertama        
          echo "quote=$quote" >> $GITHUB_ENV      
          echo "author=$author" >> $GITHUB_ENV

      - name: Debug
        run: |
          echo "Quote: ${{ env.quote }}"      
          echo "Author: ${{ env.author }}"

      - name: Send Email
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: mail.aes.my.id # Alamat server SMTP Anda
          server_port: 465 # Port server SMTP Anda
          secure: true # Menggunakan TLS
          username: ${{ secrets.MAIL_USERNAME }} # Username email
          password: ${{ secrets.MAIL_PASSWORD }} # Password email
          subject: 'Quote of the Day'
          to: 'mail.aessaputra@gmail.com,aingmauuungg@gmail.com,cloud.aessaputra@gmail.com,contact.aessaputra@gmail.com,aessaputra@aol.com,aessaputra@proton.me,aessaputra@tuta.io,aessaputra@outlook.com,aessaputra407@gmail.com,foreveryours@outlook.sg'
          from: 'info@aes.my.id' # Nama pengirim
          html_body: |
            <h3>Kata - Kata Hari Ini 📜</h3>    
            <blockquote>"${{ env.quote }}" - ${{ env.author }}</blockquote>
