name: Send Email with Quote

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Get Quote
        id: get_quote
        run: |
          response=$(curl -s -H "X-Api-Key: 3s/x4frit3GOGhj4NgYgvQ==ADMCEqbcW7LGZalp" https://api.api-ninjas.com/v1/quotes)               
          quote=$(echo $response | jq -r '.[0].quote')    
          author=$(echo $response | jq -r '.[0].author')    
          echo "quote=$quote" >> $GITHUB_ENV      
          echo "author=$author" >> $GITHUB_ENV

      - name: Send Email
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: mail.aes.my.id
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 'Quote of the Day'
          to: aessaputra@yahoo.com
          bcc: mail.aessaputra@gmail.com,aingmauuungg@gmail.com,cloud.aessaputra@gmail.com,contact.aessaputra@gmail.com,aessaputra@aol.com,aessaputra@proton.me,aessaputra@tuta.io,aessaputra@outlook.com,aessaputra407@gmail.com,foreveryours@outlook.sg
          from: 'Quotes'
          html_body: |
            <h3>📜 Kata - Kata Hari Ini 📜</h3>    
            <p style="font-style: italic; font-size: 18px; color: #333; margin: 20px 0; border-left: 4px solid #A76D4D; padding-left: 15px; line-height: 1.5;">"${{ env.quote }}" - ${{ env.author }}<p>
